### ISSUE TITLE
Inconsistent behavior, not all bubbles showing up even for simple case on iOS

### ISSUE THREAD

**Issue by eluzgin** [jesster2k10/react-native-bubble-select#13] opened 2020-08-14 19:55 UTC
Using simple case scenario below:
```
import React from 'react';
import BubbleSelect, { Bubble } from 'react-native-bubble-select';
import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const App = () => {
  return (
    <BubbleSelect
      onSelect={bubble => console.log('Selected: ', bubble.id)}
      onDeselect={bubble => console.log('Deselected: ', bubble.id)}
      width={width}
      height={height}
    >
      <Bubble id="bubble-1" text="Bubble One" />
      <Bubble id="bubble-2" text="Bubble Two" />
      <Bubble id="bubble-3" text="Bubble Three" />
      <Bubble id="bubble-4" text="Bubble Four" />
    </BubbleSelect>
  );
};
```
Not all bubbles are showing up. Sometimes it shows three, two or one on each reload.

**Comment by jesster2k10** [comment] 2020-08-17 16:18
Duplicate of #2

**Closed by jesster2k10** 2020-08-17 16:18 UTC

**Comment by rutul089** [comment] 2022-10-14 18:02
@eluzgin  Any update on this ,Did you get any solution?
